import type { Movie } from "../types/movie";

export const netflixMovies: Movie[] = [
  {
    id: 1,
    title: "The Midnight Sky",
    year: 2020,
    genre: ["Sci-Fi", "Drama"],
    director: "George Clooney",
    cast: ["George Clooney", "Felicity Jones", "David Oyelowo"],
    rating: 6.0,
    durationMin: 118,
    isNetflixOriginal: true,
    watchedDate: "2023-09-10",
    link: "https://www.imdb.com/title/tt10539608/",
    trailerLink: "https://www.youtube.com/watch?v=DxgW9LJ_rw4",
    bookmarkable: true,
  },
  {
    id: 2,
    title: "Enola Holmes",
    year: 2020,
    genre: ["Adventure", "Detective", "Family"],
    director: "Harry Bradbeer",
    cast: ["Millie Bobby Brown", "Henry Cavill", "Sam Claflin"],
    rating: 7.2,
    durationMin: 123,
    isNetflixOriginal: true,
    watchedDate: "2023-10-03",
    link: "https://www.imdb.com/title/tt7846844/",
    trailerLink: "https://www.youtube.com/watch?v=1d0Zf9sXlHk",
    bookmarkable: true,
  },
  {
    id: 3,
    title: "Extraction",
    year: 2020,
    genre: ["Action", "Thriller"],
    director: "Sam Hargrave",
    cast: ["Chris Hemsworth", "Rudhraksh Jaiswal", "Randeep Hooda"],
    rating: 6.7,
    durationMin: 117,
    isNetflixOriginal: true,
    watchedDate: "2023-08-21",
    link: "https://www.imdb.com/title/tt8936646/",
    trailerLink: "https://www.youtube.com/watch?v=L6P3nI6VnlY",
    bookmarkable: true,
  },
  {
    id: 4,
    title: "Marriage Story",
    year: 2019,
    genre: ["Drama", "Romance"],
    director: "Noah Baumbach",
    cast: ["Adam Driver", "Scarlett Johansson", "Laura Dern"],
    rating: 7.9,
    durationMin: 137,
    isNetflixOriginal: true,
    watchedDate: "2022-12-12",
    link: "https://www.imdb.com/title/tt7653254/",
    trailerLink: "https://www.youtube.com/watch?v=BHi-a1n8t7M",
    bookmarkable: true,
  },
  {
    id: 5,
    title: "The Irishman",
    year: 2019,
    genre: ["Crime", "Drama"],
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"],
    rating: 7.8,
    durationMin: 209,
    isNetflixOriginal: true,
    watchedDate: "2021-05-15",
    link: "https://www.imdb.com/title/tt1302006/",
    trailerLink: "https://www.youtube.com/watch?v=WHXxVmeGQUc",
    bookmarkable: true,
  },
  {
    id: 6,
    title: "Spiderhead",
    year: 2022,
    genre: ["Sci-Fi", "Thriller"],
    director: "Joseph Kosinski",
    cast: ["Chris Hemsworth", "Miles Teller", "Jurnee Smollett"],
    rating: 5.4,
    durationMin: 107,
    isNetflixOriginal: true,
    watchedDate: "2023-04-09",
    link: "https://www.imdb.com/title/tt9783600/",
    trailerLink: "https://www.youtube.com/watch?v=BfsG7PyI5dk",
    bookmarkable: false,
  },
  {
    id: 7,
    title: "The Old Guard",
    year: 2020,
    genre: ["Action", "Fantasy"],
    director: "Gina Prince-Bythewood",
    cast: ["Charlize Theron", "KiKi Layne", "Matthias Schoenaerts"],
    rating: 6.7,
    durationMin: 125,
    isNetflixOriginal: true,
    watchedDate: "2022-04-12",
    link: "https://www.imdb.com/title/tt7556122/",
    trailerLink: "https://www.youtube.com/watch?v=aK-X2d0lJ_s",
    bookmarkable: true,
  },
  {
    id: 8,
    title: "Murder Mystery",
    year: 2019,
    genre: ["Comedy", "Crime"],
    director: "Kyle Newacheck",
    cast: ["Adam Sandler", "Jennifer Aniston", "Luke Evans"],
    rating: 6.0,
    durationMin: 97,
    isNetflixOriginal: true,
    watchedDate: "2021-11-28",
    link: "https://www.imdb.com/title/tt1618434/",
    trailerLink: "https://www.youtube.com/watch?v=5YEVQDr2f3Q",
    bookmarkable: false,
  },
  {
    id: 9,
    title: "Always Be My Maybe",
    year: 2019,
    genre: ["Romantic Comedy"],
    director: "Nahnatchka Khan",
    cast: ["Ali Wong", "Randall Park", "James Saito"],
    rating: 6.8,
    durationMin: 102,
    isNetflixOriginal: true,
    watchedDate: "2020-06-18",
    link: "https://www.imdb.com/title/tt7374948/",
    trailerLink: "https://www.youtube.com/watch?v=iHBcWHY9lN4",
    bookmarkable: false,
  },
  {
    id: 10,
    title: "The Platform",
    year: 2019,
    genre: ["Thriller", "Drama", "Horror"],
    director: "Galder Gaztelu-Urrutia",
    cast: ["Iván Massagué", "Zorion Eguileor", "Antonia San Juan"],
    rating: 7.0,
    durationMin: 94,
    isNetflixOriginal: false,
    watchedDate: "2021-01-09",
    link: "https://www.imdb.com/title/tt8228288/",
    trailerLink: "https://www.youtube.com/watch?v=RlfooqeZcdY",
    bookmarkable: true,
  },
  {
    id: 11,
    title: "Roma",
    year: 2018,
    genre: ["Drama"],
    director: "Alfonso Cuarón",
    cast: ["Yalitza Aparicio", "Marina de Tavira"],
    rating: 7.7,
    durationMin: 135,
    isNetflixOriginal: true,
    watchedDate: "2021-03-10",
    link: "https://www.imdb.com/title/tt6155172/",
    trailerLink: "https://www.youtube.com/watch?v=6BS27ngZtxg",
    bookmarkable: true,
  },
  {
    id: 12,
    title: "Bird Box",
    year: 2018,
    genre: ["Thriller", "Sci-Fi", "Drama"],
    director: "Susanne Bier",
    cast: ["Sandra Bullock", "Trevante Rhodes"],
    rating: 6.6,
    durationMin: 124,
    isNetflixOriginal: true,
    watchedDate: "2019-01-14",
    link: "https://www.imdb.com/title/tt2737304/",
    trailerLink: "https://www.youtube.com/watch?v=o2AsIXSh2xo",
    bookmarkable: false,
  },
  {
    id: 13,
    title: "Okja",
    year: 2017,
    genre: ["Action", "Adventure", "Drama", "Sci-Fi"],
    director: "Bong Joon Ho",
    cast: ["Ahn Seo-hyun", "Tilda Swinton", "Paul Dano"],
    rating: 7.3,
    durationMin: 120,
    isNetflixOriginal: true,
    watchedDate: "2021-02-03",
    link: "https://www.imdb.com/title/tt3967856/",
    trailerLink: "https://www.youtube.com/watch?v=AjCebKn4iic",
    bookmarkable: true,
  },
  {
    id: 14,
    title: "Beasts of No Nation",
    year: 2015,
    genre: ["Drama", "War"],
    director: "Cary Joji Fukunaga",
    cast: ["Abraham Attah", "Idris Elba"],
    rating: 7.7,
    durationMin: 137,
    isNetflixOriginal: true,
    watchedDate: "2016-11-20",
    link: "https://www.imdb.com/title/tt1365050/",
    trailerLink: "https://www.youtube.com/watch?v=2xb9Ty-1frw",
    bookmarkable: true,
  },
  {
    id: 15,
    title: "Bright",
    year: 2017,
    genre: ["Action", "Fantasy", "Crime"],
    director: "David Ayer",
    cast: ["Will Smith", "Joel Edgerton", "Noomi Rapace"],
    rating: 6.3,
    durationMin: 117,
    isNetflixOriginal: true,
    watchedDate: "2018-01-15",
    link: "https://www.imdb.com/title/tt5519340/",
    trailerLink: "https://www.youtube.com/watch?v=6EZCBSsBxko",
    bookmarkable: false,
  },
  {
    id: 16,
    title: "Klaus",
    year: 2019,
    genre: ["Animation", "Comedy", "Adventure"],
    director: "Sergio Pablos",
    cast: ["Jason Schwartzman", "J.K. Simmons"],
    rating: 8.1,
    durationMin: 96,
    isNetflixOriginal: true,
    watchedDate: "2020-12-24",
    link: "https://www.imdb.com/title/tt4729430/",
    trailerLink: "https://www.youtube.com/watch?v=taE3PwurhYM",
    bookmarkable: true,
  },
  {
    id: 17,
    title: "Tall Girl",
    year: 2019,
    genre: ["Comedy", "Romance"],
    director: "Nzingha Stewart",
    cast: ["Ava Michelle", "Sabrina Carpenter"],
    rating: 5.3,
    durationMin: 101,
    isNetflixOriginal: true,
    watchedDate: "2021-04-18",
    link: "https://www.imdb.com/title/tt9252508/",
    trailerLink: "https://www.youtube.com/watch?v=aeAwNEnNU3Q",
    bookmarkable: false,
  },
  {
    id: 18,
    title: "To All the Boys I've Loved Before",
    year: 2018,
    genre: ["Romance", "Comedy"],
    director: "Susan Johnson",
    cast: ["Lana Condor", "Noah Centineo"],
    rating: 7.0,
    durationMin: 99,
    isNetflixOriginal: true,
    watchedDate: "2020-02-14",
    link: "https://www.imdb.com/title/tt3846674/",
    trailerLink: "https://www.youtube.com/watch?v=555oiY9RWM4",
    bookmarkable: true,
  },
  {
    id: 19,
    title: "The Laundromat",
    year: 2019,
    genre: ["Drama", "Comedy", "Crime"],
    director: "Steven Soderbergh",
    cast: ["Meryl Streep", "Gary Oldman", "Antonio Banderas"],
    rating: 6.3,
    durationMin: 96,
    isNetflixOriginal: true,
    watchedDate: "2020-08-16",
    link: "https://www.imdb.com/title/tt8308554/",
    trailerLink: "https://www.youtube.com/watch?v=wuBRcfe4bSo",
    bookmarkable: false,
  },
  {
    id: 20,
    title: "The Two Popes",
    year: 2019,
    genre: ["Drama", "Biography"],
    director: "Fernando Meirelles",
    cast: ["Anthony Hopkins", "Jonathan Pryce"],
    rating: 7.6,
    durationMin: 125,
    isNetflixOriginal: true,
    watchedDate: "2021-02-20",
    link: "https://www.imdb.com/title/tt8404614/",
    trailerLink: "https://www.youtube.com/watch?v=T5OhkFY1PQE",
    bookmarkable: true,
  },
  {
    id: 21,
    title: "Mute",
    year: 2018,
    genre: ["Mystery", "Sci-Fi", "Thriller"],
    director: "Duncan Jones",
    cast: ["Alexander Skarsgård", "Paul Rudd"],
    rating: 5.4,
    durationMin: 126,
    isNetflixOriginal: true,
    watchedDate: "2018-08-23",
    link: "https://www.imdb.com/title/tt1464763/",
    trailerLink: "https://www.youtube.com/watch?v=iwROgK94zcM",
    bookmarkable: false,
  },
  {
    id: 22,
    title: "Triple Frontier",
    year: 2019,
    genre: ["Action", "Adventure", "Crime"],
    director: "J.C. Chandor",
    cast: ["Ben Affleck", "Oscar Isaac", "Charlie Hunnam"],
    rating: 6.4,
    durationMin: 125,
    isNetflixOriginal: true,
    watchedDate: "2020-07-15",
    link: "https://www.imdb.com/title/tt1488606/",
    trailerLink: "https://www.youtube.com/watch?v=Fo3yRLLrXQA",
    bookmarkable: true,
  },
  {
    id: 23,
    title: "6 Underground",
    year: 2019,
    genre: ["Action", "Thriller"],
    director: "Michael Bay",
    cast: ["Ryan Reynolds", "Mélanie Laurent"],
    rating: 6.1,
    durationMin: 128,
    isNetflixOriginal: true,
    watchedDate: "2020-06-28",
    link: "https://www.imdb.com/title/tt8106534/",
    trailerLink: "https://www.youtube.com/watch?v=YLE85olJjp8",
    bookmarkable: false,
  },
  {
    id: 24,
    title: "Project Power",
    year: 2020,
    genre: ["Action", "Sci-Fi", "Crime"],
    director: "Henry Joost, Ariel Schulman",
    cast: ["Jamie Foxx", "Joseph Gordon-Levitt"],
    rating: 6.0,
    durationMin: 113,
    isNetflixOriginal: true,
    watchedDate: "2021-01-05",
    link: "https://www.imdb.com/title/tt7550000/",
    trailerLink: "https://www.youtube.com/watch?v=xw1vQgVaYNQ",
    bookmarkable: true,
  },
  {
    id: 25,
    title: "The Invisible Guest",
    year: 2016,
    genre: ["Thriller", "Mystery"],
    director: "Oriol Paulo",
    cast: ["Mario Casas", "Ana Wagener"],
    rating: 8.1,
    durationMin: 106,
    isNetflixOriginal: false,
    watchedDate: "2018-09-14",
    link: "https://www.imdb.com/title/tt4857264/",
    trailerLink: "https://www.youtube.com/watch?v=epCg2RbyF80",
    bookmarkable: true,
  },
  {
    id: 26,
    title: "The Trial of the Chicago 7",
    year: 2020,
    genre: ["Drama", "History", "Thriller"],
    director: "Aaron Sorkin",
    cast: ["Eddie Redmayne", "Sacha Baron Cohen"],
    rating: 7.8,
    durationMin: 129,
    isNetflixOriginal: true,
    watchedDate: "2021-02-28",
    link: "https://www.imdb.com/title/tt1070874/",
    trailerLink: "https://www.youtube.com/watch?v=FVb6EdKDBfU",
    bookmarkable: false,
  },
  {
    id: 27,
    title: "The Perfection",
    year: 2018,
    genre: ["Drama", "Horror", "Thriller"],
    director: "Richard Shepard",
    cast: ["Allison Williams", "Logan Browning"],
    rating: 6.2,
    durationMin: 90,
    isNetflixOriginal: true,
    watchedDate: "2019-06-06",
    link: "https://www.imdb.com/title/tt7772582/",
    trailerLink: "https://www.youtube.com/watch?v=q57D6kF5B1k",
    bookmarkable: true,
  },
  {
    id: 28,
    title: "The Fundamentals of Caring",
    year: 2016,
    genre: ["Drama", "Comedy"],
    director: "Rob Burnett",
    cast: ["Paul Rudd", "Craig Roberts", "Selena Gomez"],
    rating: 7.3,
    durationMin: 97,
    isNetflixOriginal: true,
    watchedDate: "2018-07-20",
    link: "https://www.imdb.com/title/tt2452386/",
    trailerLink: "https://www.youtube.com/watch?v=ODhMdujZeEY",
    bookmarkable: false,
  },
  {
    id: 29,
    title: "Set It Up",
    year: 2018,
    genre: ["Romantic Comedy"],
    director: "Claire Scanlon",
    cast: ["Zoey Deutch", "Glen Powell"],
    rating: 6.5,
    durationMin: 105,
    isNetflixOriginal: true,
    watchedDate: "2019-08-25",
    link: "https://www.imdb.com/title/tt5304992/",
    trailerLink: "https://www.youtube.com/watch?v=X-eRc9PF3TU",
    bookmarkable: true,
  },
  {
    id: 30,
    title: "The Silence",
    year: 2019,
    genre: ["Horror", "Thriller"],
    director: "John R. Leonetti",
    cast: ["Kiernan Shipka", "Stanley Tucci"],
    rating: 5.3,
    durationMin: 90,
    isNetflixOriginal: true,
    watchedDate: "2020-04-11",
    link: "https://www.imdb.com/title/tt7315484/",
    trailerLink: "https://www.youtube.com/watch?v=Y-ufZuqTd5c",
    bookmarkable: false,
  },
  {
    id: 31,
    title: "Wheelman",
    year: 2017,
    genre: ["Action", "Thriller"],
    director: "Jeremy Rush",
    cast: ["Frank Grillo", "Caitlin Carmichael"],
    rating: 6.4,
    durationMin: 82,
    isNetflixOriginal: true,
    watchedDate: "2018-04-07",
    link: "https://www.imdb.com/title/tt5723282/",
    trailerLink: "https://www.youtube.com/watch?v=q6q_YbL7iQ8",
    bookmarkable: true,
  },
  {
    id: 32,
    title: "The Babysitter",
    year: 2017,
    genre: ["Comedy", "Horror"],
    director: "McG",
    cast: ["Judah Lewis", "Samara Weaving"],
    rating: 6.3,
    durationMin: 85,
    isNetflixOriginal: true,
    watchedDate: "2018-11-01",
    link: "https://www.imdb.com/title/tt4225622/",
    trailerLink: "https://www.youtube.com/watch?v=qibY77AWlUc",
    bookmarkable: false,
  },
  {
    id: 33,
    title: "Polar",
    year: 2019,
    genre: ["Action", "Crime"],
    director: "Jonas Åkerlund",
    cast: ["Mads Mikkelsen", "Vanessa Hudgens"],
    rating: 6.3,
    durationMin: 118,
    isNetflixOriginal: true,
    watchedDate: "2019-07-13",
    link: "https://www.imdb.com/title/tt4139588/",
    trailerLink: "https://www.youtube.com/watch?v=oMHwRal-AR8",
    bookmarkable: true,
  },
  {
    id: 34,
    title: "I Am Mother",
    year: 2019,
    genre: ["Drama", "Sci-Fi", "Thriller"],
    director: "Grant Sputore",
    cast: ["Clara Rugaard", "Hilary Swank"],
    rating: 6.7,
    durationMin: 113,
    isNetflixOriginal: true,
    watchedDate: "2020-05-09",
    link: "https://www.imdb.com/title/tt6292852/",
    trailerLink: "https://www.youtube.com/watch?v=N5BKctcZxrM",
    bookmarkable: false,
  },
  {
    id: 35,
    title: "The King",
    year: 2019,
    genre: ["Biography", "Drama", "History"],
    director: "David Michôd",
    cast: ["Timothée Chalamet", "Joel Edgerton"],
    rating: 7.2,
    durationMin: 140,
    isNetflixOriginal: true,
    watchedDate: "2020-10-04",
    link: "https://www.imdb.com/title/tt7984766/",
    trailerLink: "https://www.youtube.com/watch?v=yMJnsTx-TBg",
    bookmarkable: false,
  },
  {
    id: 36,
    title: "The Outlaw King",
    year: 2018,
    genre: ["Action", "Drama", "History"],
    director: "David Mackenzie",
    cast: ["Chris Pine", "Stephen Dillane"],
    rating: 6.9,
    durationMin: 121,
    isNetflixOriginal: true,
    watchedDate: "2019-03-18",
    link: "https://www.imdb.com/title/tt6679794/",
    trailerLink: "https://www.youtube.com/watch?v=Q-G1BME8FKw",
    bookmarkable: true,
  },
  {
    id: 37,
    title: "The Princess Switch",
    year: 2018,
    genre: ["Romantic Comedy"],
    director: "Mike Rohl",
    cast: ["Vanessa Hudgens", "Sam Palladio"],
    rating: 6.0,
    durationMin: 101,
    isNetflixOriginal: true,
    watchedDate: "2019-12-20",
    link: "https://www.imdb.com/title/tt8954732/",
    trailerLink: "https://www.youtube.com/watch?v=7jC0AyT_h8g",
    bookmarkable: false,
  },
  {
    id: 38,
    title: "The Knight Before Christmas",
    year: 2019,
    genre: ["Romantic Comedy", "Fantasy"],
    director: "Monika Mitchell",
    cast: ["Vanessa Hudgens", "Josh Whitehouse"],
    rating: 5.5,
    durationMin: 92,
    isNetflixOriginal: true,
    watchedDate: "2020-11-25",
    link: "https://www.imdb.com/title/tt9866072/",
    trailerLink: "https://www.youtube.com/watch?v=aCsaLlxBhd0",
    bookmarkable: true,
  },
  {
    id: 39,
    title: "El Camino: A Breaking Bad Movie",
    year: 2019,
    genre: ["Crime", "Drama", "Thriller"],
    director: "Vince Gilligan",
    cast: ["Aaron Paul", "Jesse Plemons", "Krysten Ritter"],
    rating: 7.3,
    durationMin: 122,
    isNetflixOriginal: true,
    watchedDate: "2020-05-02",
    link: "https://www.imdb.com/title/tt9243946/",
    trailerLink: "https://www.youtube.com/watch?v=1JLUn2DFW4w",
    bookmarkable: false,
  },
  {
    id: 40,
    title: "The Highwaymen",
    year: 2019,
    genre: ["Crime", "Drama", "Thriller"],
    director: "John Lee Hancock",
    cast: ["Kevin Costner", "Woody Harrelson"],
    rating: 6.9,
    durationMin: 132,
    isNetflixOriginal: true,
    watchedDate: "2020-01-10",
    link: "https://www.imdb.com/title/tt1860242/",
    trailerLink: "https://www.youtube.com/watch?v=aH6vC-BBKOc",
    bookmarkable: false,
  }
];
